notwicias/urls.py
from django.conf.urls import url

from notwicias import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bot/start', views.start_bot, name='start_bot'),
    url(r'^category/(?P<category_id>[0-9]{1})/$', views.category, name='category'),
    url(r'^signin', views.sign_in, name='sign_in'),
    url(r'^login', views.log_in, name='log_in'),
    url(r'^logout', views.log_out, name='log_out'),
    url(r'^most/(?P<type>[\w-]+)/$', views.most, name='most'),
    url(r'^manage', views.manage, name='manage'),
    url(r'^modify/(?P<group_id>[0-9]{1})/$', views.modify, name='modify'),
]

twitterbot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^notwicias/', include('notwicias.urls', namespace='notwicias')),
]

notwicias/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Tweet(models.Model):
    twitter_id = models.BigIntegerField(unique=True)
    username = models.CharField(max_length=25)
    user = models.CharField(max_length=25)
    language = models.CharField(max_length=4)
    retweets = models.IntegerField()
    favorites = models.IntegerField()
    coordinates = models.CharField(max_length=50, null=True)
    text = models.CharField(max_length=160)
    date = models.DateField()
    time = models.TimeField()
    category = models.SmallIntegerField()

    def __unicode__(self):
        return "Twitter ID: {}; Text: {}".format(self.twitter_id, self.text.encode('ascii', 'ignore').decode('ascii'))


class TwitterUser(models.Model):
    name = models.CharField(max_length=15, unique=True)
    valid = models.BooleanField()

    def __str__(self):
        return self.name


class UserRelation(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(TwitterUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + ", " + str(self.group)

notwicias/forms.py
from django import forms


class SignInForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20, min_length=3)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=12, min_length=8)
    password2 = forms.CharField(label='Repite password', widget=forms.PasswordInput, max_length=12, min_length=8)
    email = forms.EmailField(label='Email', max_length=50)

notwicias/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth import authenticate
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from notwicias.bot import Bot
from notwicias.forms import SignInForm
from notwicias.models import Tweet, UserRelation, TwitterUser
from django.contrib.auth.models import User


def index(request):
    LAST_NUM = 5
    last_tweets_c0 = Tweet.objects.filter(category=0).order_by('-twitter_id')[:LAST_NUM]
    last_tweets_c1 = Tweet.objects.filter(category=1).order_by('-twitter_id')[:LAST_NUM]
    last_tweets_c2 = Tweet.objects.filter(category=2).order_by('-twitter_id')[:LAST_NUM]
    last_tweets_c3 = Tweet.objects.filter(category=3).order_by('-twitter_id')[:LAST_NUM]
    last_tweets_c4 = Tweet.objects.filter(category=4).order_by('-twitter_id')[:LAST_NUM]

    context = {'last_tweets_c0': last_tweets_c0, 'last_tweets_c1': last_tweets_c1, 'last_tweets_c2': last_tweets_c2,
               'last_tweets_c3': last_tweets_c3, 'last_tweets_c4': last_tweets_c4}
    return render(request, 'notwicias/index.html', context)


def category(request, category_id):
    category_set = Tweet.objects.filter(category=category_id).order_by('-twitter_id')[:5]
    return render(request, 'notwicias/category.html', {'category_set': category_set, 'category_id': category_id})


def start_bot(request):
    b = Bot()
    b.loop()
    return HttpResponse("Server running")


def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data
            if data['password1'] == data['password2']:
                try:
                    User.objects.create_user(data['username'], data['email'], data['password1'])
                    return HttpResponse('OK')
                except IntegrityError:
                    return HttpResponse('El nombre de usuario ya existe.')
            else:
                return HttpResponse('Los passwords no coinciden.')
        else:
            return HttpResponse('No se cumplen los requisitos de campos.')
    else:
        form = SignInForm()
        return render(request, 'notwicias/signin.html', {'form': form})


def log_in(request):
    if request.method == 'POST':
        form = request.POST
        user = authenticate(username=form['username'], password=form['password'])
        if user is not None:
            request.session['username'] = form['username']
            request.session['user_id'] = user.id
            return redirect('/notwicias')
        else:
            return HttpResponse('Autenticación fallida.')
    else:
        return HttpResponse('Petición incorrecta')


def log_out(request):
    request.session.flush()
    return redirect('/notwicias')


def most(request, type):
    MAX_TWEETS = 5
    if type == 'favorites':
        type = 'Favoritos'
        tweet_list = Tweet.objects.order_by('-favorites')[:MAX_TWEETS]
    elif type == 'retweets':
        type = 'Retuiteados'
        tweet_list = Tweet.objects.order_by('-retweets')[:MAX_TWEETS]
    return render(request, 'notwicias/most.html', {'type': type, 'tweet_list': tweet_list})


def manage(request):
    if 'username' in request.session:
        group_list = UserRelation.objects.filter(user=request.session['user_id']) # algode IDs no va bé aquí, revisar
        exclude_list = TwitterUser.objects.all()
        print group_list
        return render(request, 'notwicias/manage.html', {'group_list': group_list, 'exclude_list': exclude_list})
    else:
        return redirect('/notwicias')


def modify(request, group_id):
    group = UserRelation.objects.filter(user=request.session['user_id'], group=group_id)
    if not group:
        user_object = User.objects.get(id=request.session['user_id'])
        group_object = TwitterUser.objects.get(id=group_id)
        new_relation = UserRelation(user=user_object, group=group_object)
        new_relation.save()
    else:
        UserRelation.objects.filter(user=request.session['user_id'], group=group_id).delete()
    return redirect('/notwicias/manage')

notwicias/templates/notwicias/category.html
{% include "notwicias/include/header.html" %}

<div class="container">
    <div class="page-header">
        <h1>{{ category_id }}
            <small> Categorías</small>
        </h1>
    </div>

    {% for tweet in category_set %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}
</div>

{% include "notwicias/include/footer.html" %}

<!--
politica = 1
internacional = 2
esports = 3
tecnologia = 4
transports = 5
else = 0
-->

notwicias/templates/notwicias/include/footer.html
<div style="margin-top:51px"></div>

<div class="jumbotron" style="margin-bottom:0px">
    <div class="container">
        <p>&copy; 2017 Notwícias. Todos los derechos reservados.</p>
        <br>
        <p>Proyecto Django</p>
    </div>
</div>

</body>
</html>

notwicias/templates/notwicias/include/header.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Portal web de Notwicias</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'notwicias:index' %}">Notwícias</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'notwicias:index' %}">Portada</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Categorías<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'notwicias:category' category_id='0' %}">General</a></li>
                        <li><a href="{% url 'notwicias:category' category_id='1' %}">Política</a></li>
                        <li><a href="{% url 'notwicias:category' category_id='2' %}">Internacional</a></li>
                        <li><a href="{% url 'notwicias:category' category_id='3' %}">Tecnología</a></li>
                        <li><a href="{% url 'notwicias:category' category_id='4' %}">Deportes</a></li>
                        <li><a href="{% url 'notwicias:category' category_id='5' %}">Transportes</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Los más<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'notwicias:most' type='favorites' %}">Favoritos</a></li>
                        <li><a href="{% url 'notwicias:most' type='retweets' %}">Retuiteados</a></li>
                    </ul>
                </li>
            </ul>
            {% if 'username' in request.session %}
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><span class="glyphicon glyphicon-lock"></span> Área privada<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="myarea.php">Mi portada</a></li>
                        <li><a href="manage_area.php">Configuración</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'notwicias:log_out' %}"><span class="glyphicon glyphicon-off"></span> Salir
                    ({{ request.session.username }})</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#" data-toggle="modal" data-target="#login"><span class="glyphicon glyphicon-user"></span>
                    Entrar</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

<!-- Margen superior equivalente a altura menú -->
<div style="margin-top:51px"></div>

<!-- alerta en cas de no estar logat i menú de login -->
{% if not 'username' in request.session %}
<div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <strong>Atención!</strong> Para una personalización de notícias <a href="#" class="alert-link">entra con tu
    cuenta.</a>
</div>
{% endif %}

<div class="container">
    <!-- Modal -->
    <div class="modal fade" id="login" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span class="glyphicon glyphicon-lock"></span> Control de acceso al sistema
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Entra tus credenciales.</p>
                    <form class="form-signin" action="{% url 'notwicias:log_in' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><span
                                    class="glyphicon glyphicon-user"></span></span>
                            <input type="text" class="form-control" placeholder="Username"
                                   aria-describedby="basic-addon1" name="username">
                        </div>
                        <br>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon2"><span
                                    class="glyphicon glyphicon-lock"></span></span>
                            <input type="password" class="form-control" placeholder="Password"
                                   aria-describedby="basic-addon2" name="password">
                        </div>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" value="remember-me"> Recuérdame
                            </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
                    </form>

                </div>
                <div class="modal-footer">
                    <a href="signin.php">Registrarse</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

notwicias/templates/notwicias/index.html
{% include "notwicias/include/header.html" %}

{% if not 'username' in request.session %}
<div class="container">
    <div class="jumbotron">
        <h1>Bienvenido a Notwícias</h1>
        <p>El portal de notícias actualizado 24 horas vía Twitter.</p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Date de alta</a>
    </div>
</div>
{% endif %}

<div class="container">
    <div class="page-header">
        <h1>Portada
            <small> Últimas notícias</small>
        </h1>
    </div>

    <h2>Política</h2>
    {% for tweet in last_tweets_c0 %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}

    <h2>Internacional</h2>
    {% for tweet in last_tweets_c1 %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}

    <h2>Deportes</h2>
    {% for tweet in last_tweets_c2 %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}

    <h2>Tecnología</h2>
    {% for tweet in last_tweets_c3 %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}

    <h2>Transportes</h2>
    {% for tweet in last_tweets_c4 %}
    <div class='col-sm-6'><h3>{{ tweet.user }} ({{ tweet.date }})</h3>
        {{ tweet.text }}<br />
        {{ tweet.date }} {{ tweet.time }}<br /><br /><hr>
    </div>
    {% endfor %}


</div>

{% include "notwicias/include/footer.html" %}

notwicias/templates/notwicias/manage.html
{% include "notwicias/include/header.html" %}

<div class="container">
    <div class="page-header">
        <h1>Gestión de mi portada
            <small> Área privada</small>
        </h1>
    </div>
    <p>A continuación puedes añadir o quitar los grupos que aparecen en tu portada. Si lo deseas, puedes hacer una
        petición en el recuadro de abajo de un grupo que no esté disponible.</p>

    <div class="row">
        <div class="col-md-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">Grupos suscritos</div>
                <div class="panel-body">
                    {% for group in group_list %}
                    <a href="modify/{{ group.id }}">
                        <button type="button" class="btn btn-default" style="margin-right:5px;margin-bottom:5px">
                            {{ group.group }}
                            <span class="glyphicon glyphicon-minus" style="margin-left:10px"></span></button>
                    </a>
                    {% empty %}
                    <p>Actualmente no estas suscrito a ningún grupo.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">Añadir grupo</div>
                <div class="panel-body">
                    {% for exclude in exclude_list %}
                    <a href="modify/{{ exclude.id }}">
                        <button type="button" class="btn btn-success" style="margin-right:5px;margin-bottom:5px">
                            {{ exclude }}
                            <span class="glyphicon glyphicon-plus" style="margin-left:10px"></span></button>
                    </a>
                    {% empty %}
                    <p>Actualmente no estas suscrito a ningún grupo.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Nuevo grupo</h2>
            <p>Introduce el nombre del grupo a añadir:</p>
            <form class="form-inline" action="operations/add_group.php" method="post">
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon6"><span
                            class="glyphicon glyphicon-plus"></span></span>
                    <input type="text" class="form-control" placeholder="Nom del grup" name="name">
                </div>
                <button type="submit" class="btn btn-default">Añadir</button>
            </form>
        </div>
    </div>
</div>

{% include "notwicias/include/footer.html" %}

notwicias/templates/notwicias/most.html
{% include "notwicias/include/header.html" %}

<div class="container">
    <div class="page-header">
        <h1>{{ type }}
            <small> Los más</small>
        </h1>
    </div>

    <table class="table-striped table-bordered">
        <tr>
            <th>Posición</th>
            {% if type == 'Retuiteados' %}
            <th>Retweets</th>
            {% elif type == 'Favoritos' %}
            <th>Favoritos</th>
            {% endif %}
            <th>Autor</th>
            <th>Texto</th>
            <th>Fecha</th>
        </tr>

        {% for tweet in tweet_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            {% if type == 'Retuiteados' %}
            <td>{{ tweet.retweets }}</td>
            {% elif type == 'Favoritos' %}
            <td>{{ tweet.favorites }}</td>
            {% endif %}
            <td>{{ tweet.user }}</td>
            <td>{{ tweet.text }}</td>
            <td>{{ tweet.date }}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% include "notwicias/include/footer.html" %}

notwicias/templates/notwicias/signin.html
{% include "notwicias/include/header.html" %}

<div class="container">
    <div class="page-header">
        <h1>Formulario de registro
            <small> Acceso al sistema</small>
        </h1>
    </div>
    <p>Llena los campos del formulario para crear tu usuario.</p>

    <form data-toggle="validator" role="form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Registrar" />
        <!--<div class="form-group">
            <label for="inputName" class="control-label">Nombre de usuario</label>
            <input type="text" class="form-control" id="inputName" placeholder="Username" name="username" required>
        </div>

        <div class="form-group">
            <label for="inputEmail" class="control-label">Correo electrónico</label>

            <input type="email" class="form-control" id="inputEmail" placeholder="nombre@host.dominio" name="email"
                   data-error="L'adreça de correu és invàlida" required>
            <div class="help-block with-errors"></div>
        </div>

        <div class="form-group">
            <label for="inputPassword" class="control-label">Password</label>
            <div class="row">
                <div class="form-group col-sm-6">
                    <input type="password" data-minlength="8" class="form-control" id="inputPassword"
                           placeholder="Password" name="password" required>
                    <span class="help-block">La longitud mínima del password es de 8</span>
                </div>
                <div class="form-group col-sm-6">
                    <input type="password" class="form-control" id="inputPasswordConfirm" data-match="#inputPassword"
                           data-match-error="Els passwords no coincideixen" placeholder="Repetición de password"
                           name="password2" required>
                    <div class="help-block with-errors"></div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="terms" data-error="Heu d'acceptar les condicions d'ús" name="check"
                           required>
                    Acepto las condiciones de uso
                </label>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Registrar</button>
        </div>-->
    </form>

</div>

{% include "notwicias/include/footer.html" %}